# Generated by Django 5.1.4 on 2025-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='compassionate_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='maternity_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='paternity_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='unpaid_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Unpaid', 'Unpaid'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Compassionate', 'Compassionate'), ('Other', 'Other')], max_length=50),
        ),
    ]
