# Generated by Django 5.1.4 on 2025-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavebalance_compassionate_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='emergency_leave_balance',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='personal_leave_balance',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Unpaid', 'Unpaid'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Compassionate', 'Compassionate'), ('Personal Leave', 'Personal Leave'), ('Emergency Leave', 'Emergency Leave'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='compassionate_leave_balance',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
