# Generated by Django 5.1.4 on 2025-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavebalance_emergency_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='other_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
