# Generated by Django 5.1.4 on 2025-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leavebalance_other_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='other_leave_balance',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
