# Generated by Django 5.1.4 on 2025-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_alter_leave_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='remarks',
            field=models.TextField(blank=True, default='Awaiting approval'),
        ),
    ]
