# Generated by Django 5.1.4 on 2025-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Company Phone Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Contact Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Relation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_town_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Home Town Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email'),
        ),
    ]
