# Generated by Django 5.1.4 on 2025-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_date_joined_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emirates_id_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Emirates ID Expiry'),
        ),
    ]
