# Generated by Django 5.1.4 on 2025-02-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='total_workable_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Total Workable Days'),
        ),
    ]
