# Generated by Django 5.1.4 on 2025-05-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_salarydetails_other_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mother Name'),
        ),
    ]
