# Generated by Django 5.1.4 on 2025-02-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_payrollrecord_total_workable_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryrevision',
            old_name='revise_salary_effective_from',
            new_name='revised_salary_effective_from',
        ),
    ]
