# Generated by Django 5.1.4 on 2025-01-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_emirates_id_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetails',
            name='account_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account No'),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SWIFT Code'),
        ),
    ]
