# Generated by Django 5.1.4 on 2025-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_revise_salary_effective_from_salaryrevision_revised_salary_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Basic Salary'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daily Salary'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gross Salary'),
        ),
    ]
