# Generated by Django 5.1.4 on 2025-01-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_salarydetails_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Children'),
        ),
    ]
