# Generated by Django 5.1.4 on 2025-01-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Expiry Date'),
        ),
    ]
