# Generated by Django 5.1.4 on 2025-02-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_payrollrecord_basic_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='basic_salary',
            new_name='current_basic_salary',
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='daily_salary',
            new_name='current_daily_salary',
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='gross_salary',
            new_name='current_gross_salary',
        ),
    ]
