# Generated by Django 5.1.4 on 2025-02-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_basic_salary_payrollrecord_current_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='normal_overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Normal Overtime Amount'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Overtime Amount'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='unpaid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unpaid Amount'),
        ),
    ]
