# Generated by Django 5.1.4 on 2025-01-23 09:06

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_insurance_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/', validators=[employees.models.Employee.validate_file_type], verbose_name='Photo'),
        ),
    ]
