# Generated by Django 5.1.4 on 2025-01-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetails',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Other Allowance'),
        ),
    ]
