# Generated by Django 5.1.4 on 2025-01-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_salarydetails_other_allowance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
