# Generated by Django 5.1.4 on 2025-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_payrollrecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='example@liya.ae', max_length=254, null=True, verbose_name='Company Email'),
        ),
    ]
