# Generated by Django 5.1.4 on 2025-01-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='normal_overtime_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Normal Overtime Days'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='overtime_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Holiday Overtime Days'),
        ),
    ]
