# Generated by Django 5.1.4 on 2025-02-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_payrollrecord_normal_overtime_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revised_basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Revised Basic Salary')),
                ('revised_housing_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Revised Housing Allowance')),
                ('revised_transport_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Revised Transport Allowance')),
                ('revised_other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revised Other Allowance')),
                ('revision_date', models.DateTimeField(auto_now_add=True, verbose_name='Revision Date')),
                ('revision_reason', models.TextField(verbose_name='Reason for Revision')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='employees.employee')),
            ],
        ),
    ]
