# Generated by Django 5.1.4 on 2025-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_salaryrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrevision',
            name='previous_basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Previous Basic Salary'),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='previous_gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Previous Gross Salary'),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='previous_housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Previous Housing Allowance'),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='previous_other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Previous Other Allowance'),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='previous_transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Previous Transport Allowance'),
        ),
    ]
