# Generated by Django 5.1.4 on 2025-02-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_salaryrevision_previous_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrevision',
            name='revised_gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revised Gross Salary'),
        ),
    ]
