# Generated by Django 5.1.4 on 2025-02-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(choices=[('Liya', 'Liya'), ('Opera', 'Opera'), ('Fusion', 'Fusion')], default='Liya', max_length=255),
        ),
    ]
