# Generated by Django 5.1.4 on 2025-05-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Both', 'Both')], default='Employee', max_length=10),
        ),
    ]
