# .github/workflows/deploy.yml
name: CI/CD Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 5.30.204.180 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        run: ssh -i ~/.ssh/id_rsa Administrator@5.30.204.180 'powershell -File C:\deploy\deploy.ps1'
